import { StyleSheet } from 'react-native';

export const colors = {
  background: '#1d1d1d',
  backgroundSecondary: '#2e2e2e',
  surface: 'rgba(45, 45, 45, 0.9)',
  neon: '#00ffcc',
  neonDim: 'rgba(0, 255, 204, 0.3)',
  primary: '#ff007f',
  primaryGradientEnd: '#ff7f00',
  text: '#f0f0f0',
  textSecondary: '#aaaaaa',
  correct: '#00cc66',
  incorrect: '#ff3333',
  border: 'rgba(0, 255, 204, 0.3)',
  white: '#ffffff',
};

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    padding: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: 'bold',
    color: colors.neon,
    textAlign: 'center',
    textShadowColor: colors.neon,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 16,
    color: colors.textSecondary,
    textAlign: 'center',
    marginBottom: 30,
  },
  heading: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.neon,
    textAlign: 'center',
    marginBottom: 20,
    textShadowColor: colors.neon,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  card: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.neon,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginVertical: 8,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'bold',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingVertical: 14,
    paddingHorizontal: 24,
    alignItems: 'center',
    marginVertical: 8,
    borderWidth: 1,
    borderColor: colors.neon,
  },
  secondaryButtonText: {
    color: colors.neon,
    fontSize: 16,
    fontWeight: '600',
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 12,
  },
  label: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: 6,
  },
  questionText: {
    fontSize: 20,
    color: colors.text,
    textAlign: 'center',
    marginBottom: 24,
    lineHeight: 28,
  },
  feedbackCorrect: {
    backgroundColor: 'rgba(0, 204, 102, 0.15)',
    borderColor: colors.correct,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  feedbackIncorrect: {
    backgroundColor: 'rgba(255, 51, 51, 0.15)',
    borderColor: colors.incorrect,
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    marginTop: 12,
  },
  feedbackText: {
    color: colors.text,
    textAlign: 'center',
    fontSize: 15,
  },
});
